import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import {
  VisibleWrapperFooter,
  VisibleWrapperNavbar,
} from "@/lib/VisibleWrapper";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GeStocker",
  description: "Generated by GeStocker",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <VisibleWrapperNavbar>
            <Navbar />
          </VisibleWrapperNavbar>
          <Toaster position="top-right" richColors duration={2000}/>
          <div className="min-h-screen">{children}</div>
          <VisibleWrapperFooter>
            <Footer />
          </VisibleWrapperFooter>
        </AuthProvider>
      </body>
    </html>
  );
}
